application: cuhc-bdoty
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /static
  static_dir: static

- url: /css
  static_dir: static/css

- url: /assets
  static_dir: static/assets

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /ext
  static_dir: static/ext

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /webapp\.json
  static_files: static/webapp.json
  upload: static/webapp\.json

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
